# Generated by Django 4.0.3 on 2022-04-05 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critics', '0003_alter_review_body_alter_review_headline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Zero'), (1, 'Un'), (2, 'Deux'), (3, 'Trois'), (4, 'Quatre'), (5, 'Cinq')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note'),
        ),
    ]
